package model.pojo;
// Generated Oct 2, 2012 7:10:27 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * ChiTietKhuyenMai generated by hbm2java
 */
public class ChiTietKhuyenMai  implements java.io.Serializable {


     private ChiTietKhuyenMaiId id;
     private SanPham sanPham;
     private KhuyenMai khuyenMai;
     private Date ngayBatDau;
     private Date ngayKetThuc;

    public ChiTietKhuyenMai() {
    }

	
    public ChiTietKhuyenMai(ChiTietKhuyenMaiId id, SanPham sanPham, KhuyenMai khuyenMai) {
        this.id = id;
        this.sanPham = sanPham;
        this.khuyenMai = khuyenMai;
    }
    public ChiTietKhuyenMai(ChiTietKhuyenMaiId id, SanPham sanPham, KhuyenMai khuyenMai, Date ngayBatDau, Date ngayKetThuc) {
       this.id = id;
       this.sanPham = sanPham;
       this.khuyenMai = khuyenMai;
       this.ngayBatDau = ngayBatDau;
       this.ngayKetThuc = ngayKetThuc;
    }
   
    public ChiTietKhuyenMaiId getId() {
        return this.id;
    }
    
    public void setId(ChiTietKhuyenMaiId id) {
        this.id = id;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public KhuyenMai getKhuyenMai() {
        return this.khuyenMai;
    }
    
    public void setKhuyenMai(KhuyenMai khuyenMai) {
        this.khuyenMai = khuyenMai;
    }
    public Date getNgayBatDau() {
        return this.ngayBatDau;
    }
    
    public void setNgayBatDau(Date ngayBatDau) {
        this.ngayBatDau = ngayBatDau;
    }
    public Date getNgayKetThuc() {
        return this.ngayKetThuc;
    }
    
    public void setNgayKetThuc(Date ngayKetThuc) {
        this.ngayKetThuc = ngayKetThuc;
    }




}


