package model.pojo;
// Generated Sep 28, 2012 7:25:13 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SanPham generated by hbm2java
 */
public class SanPham  implements java.io.Serializable {


     private String maSanPham;
     private HangSanXuat hangSanXuat;
     private TinhTrangSanPham tinhTrangSanPham;
     private String tenSanPham;
     private String hinhAnh;
     private Double gia;
     private Integer soLuongTon;
     private Date ngayCapNhat;
     private Set chiTietDonHangs = new HashSet(0);
     private Set chiTietKhuyenMais = new HashSet(0);
     private Set linhKiens = new HashSet(0);
     private Set laptops = new HashSet(0);

    public SanPham() {
    }

	
    public SanPham(String maSanPham) {
        this.maSanPham = maSanPham;
    }
    public SanPham(String maSanPham, HangSanXuat hangSanXuat, TinhTrangSanPham tinhTrangSanPham, String tenSanPham, String hinhAnh, Double gia, Integer soLuongTon, Date ngayCapNhat, Set chiTietDonHangs, Set chiTietKhuyenMais, Set linhKiens, Set laptops) {
       this.maSanPham = maSanPham;
       this.hangSanXuat = hangSanXuat;
       this.tinhTrangSanPham = tinhTrangSanPham;
       this.tenSanPham = tenSanPham;
       this.hinhAnh = hinhAnh;
       this.gia = gia;
       this.soLuongTon = soLuongTon;
       this.ngayCapNhat = ngayCapNhat;
       this.chiTietDonHangs = chiTietDonHangs;
       this.chiTietKhuyenMais = chiTietKhuyenMais;
       this.linhKiens = linhKiens;
       this.laptops = laptops;
    }
   
    public String getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(String maSanPham) {
        this.maSanPham = maSanPham;
    }
    public HangSanXuat getHangSanXuat() {
        return this.hangSanXuat;
    }
    
    public void setHangSanXuat(HangSanXuat hangSanXuat) {
        this.hangSanXuat = hangSanXuat;
    }
    public TinhTrangSanPham getTinhTrangSanPham() {
        return this.tinhTrangSanPham;
    }
    
    public void setTinhTrangSanPham(TinhTrangSanPham tinhTrangSanPham) {
        this.tinhTrangSanPham = tinhTrangSanPham;
    }
    public String getTenSanPham() {
        return this.tenSanPham;
    }
    
    public void setTenSanPham(String tenSanPham) {
        this.tenSanPham = tenSanPham;
    }
    public String getHinhAnh() {
        return this.hinhAnh;
    }
    
    public void setHinhAnh(String hinhAnh) {
        this.hinhAnh = hinhAnh;
    }
    public Double getGia() {
        return this.gia;
    }
    
    public void setGia(Double gia) {
        this.gia = gia;
    }
    public Integer getSoLuongTon() {
        return this.soLuongTon;
    }
    
    public void setSoLuongTon(Integer soLuongTon) {
        this.soLuongTon = soLuongTon;
    }
    public Date getNgayCapNhat() {
        return this.ngayCapNhat;
    }
    
    public void setNgayCapNhat(Date ngayCapNhat) {
        this.ngayCapNhat = ngayCapNhat;
    }
    public Set getChiTietDonHangs() {
        return this.chiTietDonHangs;
    }
    
    public void setChiTietDonHangs(Set chiTietDonHangs) {
        this.chiTietDonHangs = chiTietDonHangs;
    }
    public Set getChiTietKhuyenMais() {
        return this.chiTietKhuyenMais;
    }
    
    public void setChiTietKhuyenMais(Set chiTietKhuyenMais) {
        this.chiTietKhuyenMais = chiTietKhuyenMais;
    }
    public Set getLinhKiens() {
        return this.linhKiens;
    }
    
    public void setLinhKiens(Set linhKiens) {
        this.linhKiens = linhKiens;
    }
    public Set getLaptops() {
        return this.laptops;
    }
    
    public void setLaptops(Set laptops) {
        this.laptops = laptops;
    }




}


