package model.pojo;
// Generated Nov 23, 2012 11:16:33 PM by Hibernate Tools 3.2.1.GA



/**
 * ChiTietDonHang generated by hbm2java
 */
public class ChiTietDonHang  implements java.io.Serializable {


     private ChiTietDonHangId id;
     private DatHang datHang;
     private SanPham sanPham;
     private Integer tinhTrang;
     private Integer soLuong;
     private Double donGia;

    public ChiTietDonHang() {
    }

	
    public ChiTietDonHang(ChiTietDonHangId id, DatHang datHang, SanPham sanPham) {
        this.id = id;
        this.datHang = datHang;
        this.sanPham = sanPham;
    }
    public ChiTietDonHang(ChiTietDonHangId id, DatHang datHang, SanPham sanPham, Integer tinhTrang, Integer soLuong, Double donGia) {
       this.id = id;
       this.datHang = datHang;
       this.sanPham = sanPham;
       this.tinhTrang = tinhTrang;
       this.soLuong = soLuong;
       this.donGia = donGia;
    }
   
    public ChiTietDonHangId getId() {
        return this.id;
    }
    
    public void setId(ChiTietDonHangId id) {
        this.id = id;
    }
    public DatHang getDatHang() {
        return this.datHang;
    }
    
    public void setDatHang(DatHang datHang) {
        this.datHang = datHang;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Integer getSoLuong() {
        return this.soLuong;
    }
    
    public void setSoLuong(Integer soLuong) {
        this.soLuong = soLuong;
    }
    public Double getDonGia() {
        return this.donGia;
    }
    
    public void setDonGia(Double donGia) {
        this.donGia = donGia;
    }




}


