package model.pojo;
// Generated Nov 23, 2012 11:16:33 PM by Hibernate Tools 3.2.1.GA



/**
 * KhoanGia generated by hbm2java
 */
public class KhoanGia  implements java.io.Serializable {


     private String maKhoanGia;
     private Double giaTu;
     private Double giaDen;
     private Integer tinhTrang;

    public KhoanGia() {
    }

	
    public KhoanGia(String maKhoanGia) {
        this.maKhoanGia = maKhoanGia;
    }
    public KhoanGia(String maKhoanGia, Double giaTu, Double giaDen, Integer tinhTrang) {
       this.maKhoanGia = maKhoanGia;
       this.giaTu = giaTu;
       this.giaDen = giaDen;
       this.tinhTrang = tinhTrang;
    }
   
    public String getMaKhoanGia() {
        return this.maKhoanGia;
    }
    
    public void setMaKhoanGia(String maKhoanGia) {
        this.maKhoanGia = maKhoanGia;
    }
    public Double getGiaTu() {
        return this.giaTu;
    }
    
    public void setGiaTu(Double giaTu) {
        this.giaTu = giaTu;
    }
    public Double getGiaDen() {
        return this.giaDen;
    }
    
    public void setGiaDen(Double giaDen) {
        this.giaDen = giaDen;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }




}


