package model.pojo;
// Generated Nov 23, 2012 11:16:33 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TinhTrangSanPham generated by hbm2java
 */
public class TinhTrangSanPham  implements java.io.Serializable {


     private int maTinhTrang;
     private String mota;
     private Set sanPhams = new HashSet(0);

    public TinhTrangSanPham() {
    }

	
    public TinhTrangSanPham(int maTinhTrang) {
        this.maTinhTrang = maTinhTrang;
    }
    public TinhTrangSanPham(int maTinhTrang, String mota, Set sanPhams) {
       this.maTinhTrang = maTinhTrang;
       this.mota = mota;
       this.sanPhams = sanPhams;
    }
   
    public int getMaTinhTrang() {
        return this.maTinhTrang;
    }
    
    public void setMaTinhTrang(int maTinhTrang) {
        this.maTinhTrang = maTinhTrang;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Set getSanPhams() {
        return this.sanPhams;
    }
    
    public void setSanPhams(Set sanPhams) {
        this.sanPhams = sanPhams;
    }




}


