package model.pojo;
// Generated Sep 28, 2012 7:25:13 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * DatHang generated by hbm2java
 */
public class DatHang  implements java.io.Serializable {


     private String maDonHang;
     private NhanVien nhanVien;
     private KhachHang khachHang;
     private TinhTrangDonDatHang tinhTrangDonDatHang;
     private Set chiTietDonHangs = new HashSet(0);

    public DatHang() {
    }

	
    public DatHang(String maDonHang) {
        this.maDonHang = maDonHang;
    }
    public DatHang(String maDonHang, NhanVien nhanVien, KhachHang khachHang, TinhTrangDonDatHang tinhTrangDonDatHang, Set chiTietDonHangs) {
       this.maDonHang = maDonHang;
       this.nhanVien = nhanVien;
       this.khachHang = khachHang;
       this.tinhTrangDonDatHang = tinhTrangDonDatHang;
       this.chiTietDonHangs = chiTietDonHangs;
    }
   
    public String getMaDonHang() {
        return this.maDonHang;
    }
    
    public void setMaDonHang(String maDonHang) {
        this.maDonHang = maDonHang;
    }
    public NhanVien getNhanVien() {
        return this.nhanVien;
    }
    
    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }
    public KhachHang getKhachHang() {
        return this.khachHang;
    }
    
    public void setKhachHang(KhachHang khachHang) {
        this.khachHang = khachHang;
    }
    public TinhTrangDonDatHang getTinhTrangDonDatHang() {
        return this.tinhTrangDonDatHang;
    }
    
    public void setTinhTrangDonDatHang(TinhTrangDonDatHang tinhTrangDonDatHang) {
        this.tinhTrangDonDatHang = tinhTrangDonDatHang;
    }
    public Set getChiTietDonHangs() {
        return this.chiTietDonHangs;
    }
    
    public void setChiTietDonHangs(Set chiTietDonHangs) {
        this.chiTietDonHangs = chiTietDonHangs;
    }




}


