package model.pojo;
// Generated Oct 2, 2012 7:10:27 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * KhuyenMai generated by hbm2java
 */
public class KhuyenMai  implements java.io.Serializable {


     private String maKhuyenMai;
     private String noiDungKhuyenMai;
     private Date thoiGianBatDau;
     private Date thoiGianKetThuc;
     private Integer tinhTrang;
     private Set chiTietKhuyenMais = new HashSet(0);

    public KhuyenMai() {
    }

	
    public KhuyenMai(String maKhuyenMai) {
        this.maKhuyenMai = maKhuyenMai;
    }
    public KhuyenMai(String maKhuyenMai, String noiDungKhuyenMai, Date thoiGianBatDau, Date thoiGianKetThuc, Integer tinhTrang, Set chiTietKhuyenMais) {
       this.maKhuyenMai = maKhuyenMai;
       this.noiDungKhuyenMai = noiDungKhuyenMai;
       this.thoiGianBatDau = thoiGianBatDau;
       this.thoiGianKetThuc = thoiGianKetThuc;
       this.tinhTrang = tinhTrang;
       this.chiTietKhuyenMais = chiTietKhuyenMais;
    }
   
    public String getMaKhuyenMai() {
        return this.maKhuyenMai;
    }
    
    public void setMaKhuyenMai(String maKhuyenMai) {
        this.maKhuyenMai = maKhuyenMai;
    }
    public String getNoiDungKhuyenMai() {
        return this.noiDungKhuyenMai;
    }
    
    public void setNoiDungKhuyenMai(String noiDungKhuyenMai) {
        this.noiDungKhuyenMai = noiDungKhuyenMai;
    }
    public Date getThoiGianBatDau() {
        return this.thoiGianBatDau;
    }
    
    public void setThoiGianBatDau(Date thoiGianBatDau) {
        this.thoiGianBatDau = thoiGianBatDau;
    }
    public Date getThoiGianKetThuc() {
        return this.thoiGianKetThuc;
    }
    
    public void setThoiGianKetThuc(Date thoiGianKetThuc) {
        this.thoiGianKetThuc = thoiGianKetThuc;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getChiTietKhuyenMais() {
        return this.chiTietKhuyenMais;
    }
    
    public void setChiTietKhuyenMais(Set chiTietKhuyenMais) {
        this.chiTietKhuyenMais = chiTietKhuyenMais;
    }




}


