package model.pojo;
// Generated Oct 2, 2012 7:10:27 PM by Hibernate Tools 3.2.1.GA



/**
 * LinhKien generated by hbm2java
 */
public class LinhKien  implements java.io.Serializable {


     private String maSanPham;
     private SanPham sanPham;

    public LinhKien() {
    }

    public LinhKien(String maSanPham, SanPham sanPham) {
       this.maSanPham = maSanPham;
       this.sanPham = sanPham;
    }
   
    public String getMaSanPham() {
        return this.maSanPham;
    }
    
    public void setMaSanPham(String maSanPham) {
        this.maSanPham = maSanPham;
    }
    public SanPham getSanPham() {
        return this.sanPham;
    }
    
    public void setSanPham(SanPham sanPham) {
        this.sanPham = sanPham;
    }




}


