package model.pojo;
// Generated Nov 23, 2012 11:16:33 PM by Hibernate Tools 3.2.1.GA

import java.sql.Timestamp;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * DatHang generated by hbm2java
 */
public class DatHang implements java.io.Serializable {

    private String maDonHang;
    private NhanVien nhanVien;
    private KhachHang khachHang;
    private TinhTrangDonDatHang tinhTrangDonDatHang;
    private Set chiTietDonHangs = new HashSet(0);
    private String diaChiGiaoHang;
    private String dienThoai;
    private String nguoiNhan;
    private Timestamp ngayDat;

    public DatHang() {
    }

    public DatHang(String maDonHang) {
        this.maDonHang = maDonHang;
    }

    public DatHang(String maDonHang, NhanVien nhanVien, KhachHang khachHang, TinhTrangDonDatHang tinhTrangDonDatHang, Set chiTietDonHangs) {
        this.maDonHang = maDonHang;
        this.nhanVien = nhanVien;
        this.khachHang = khachHang;
        this.tinhTrangDonDatHang = tinhTrangDonDatHang;
        this.chiTietDonHangs = chiTietDonHangs;
    }

    public String getMaDonHang() {
        return this.maDonHang;
    }

    public void setMaDonHang(String maDonHang) {
        this.maDonHang = maDonHang;
    }

    public NhanVien getNhanVien() {
        return this.nhanVien;
    }

    public void setNhanVien(NhanVien nhanVien) {
        this.nhanVien = nhanVien;
    }

    public KhachHang getKhachHang() {
        return this.khachHang;
    }

    public void setKhachHang(KhachHang khachHang) {
        this.khachHang = khachHang;
    }

    public TinhTrangDonDatHang getTinhTrangDonDatHang() {
        return this.tinhTrangDonDatHang;
    }

    public void setTinhTrangDonDatHang(TinhTrangDonDatHang tinhTrangDonDatHang) {
        this.tinhTrangDonDatHang = tinhTrangDonDatHang;
    }

    public Set getChiTietDonHangs() {
        return this.chiTietDonHangs;
    }

    public void setChiTietDonHangs(Set chiTietDonHangs) {
        this.chiTietDonHangs = chiTietDonHangs;
    }

    public String getDiaChiGiaoHang() {
        return diaChiGiaoHang;
    }

    public void setDiaChiGiaoHang(String diaChiGiaoHang) {
        this.diaChiGiaoHang = diaChiGiaoHang;
    }

    public String getDienThoai() {
        return dienThoai;
    }

    public void setDienThoai(String dienThoai) {
        this.dienThoai = dienThoai;
    }

    public String getNguoiNhan() {
        return nguoiNhan;
    }

    public void setNguoiNhan(String nguoiNhan) {
        this.nguoiNhan = nguoiNhan;
    }

    public Timestamp getNgayDat() {
        return ngayDat;
    }

    public void setNgayDat(Timestamp ngayDat) {
        this.ngayDat = ngayDat;
    }
    
}
