package model.pojo;
// Generated Oct 23, 2012 10:38:34 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * HangSanXuat generated by hbm2java
 */
public class HangSanXuat  implements java.io.Serializable {


     private String maHang;
     private String tenHang;
     private String ghiChu;
     private Integer tinhTrang;
     private Set sanPhams = new HashSet(0);

    public HangSanXuat() {
    }

	
    public HangSanXuat(String maHang) {
        this.maHang = maHang;
    }
    public HangSanXuat(String maHang, String tenHang, String ghiChu, Integer tinhTrang, Set sanPhams) {
       this.maHang = maHang;
       this.tenHang = tenHang;
       this.ghiChu = ghiChu;
       this.tinhTrang = tinhTrang;
       this.sanPhams = sanPhams;
    }
   
    public String getMaHang() {
        return this.maHang;
    }
    
    public void setMaHang(String maHang) {
        this.maHang = maHang;
    }
    public String getTenHang() {
        return this.tenHang;
    }
    
    public void setTenHang(String tenHang) {
        this.tenHang = tenHang;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public Set getSanPhams() {
        return this.sanPhams;
    }
    
    public void setSanPhams(Set sanPhams) {
        this.sanPhams = sanPhams;
    }




}


