package model.pojo;
// Generated Oct 23, 2012 10:38:34 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * KhuyenMai generated by hbm2java
 */
public class KhuyenMai  implements java.io.Serializable {


     private String maKhuyenMai;
     private String noiDungKhuyenMai;
     private Integer tinhTrang;
     private String ghiChu;
     private Set chiTietKhuyenMais = new HashSet(0);

    public KhuyenMai() {
    }

	
    public KhuyenMai(String maKhuyenMai) {
        this.maKhuyenMai = maKhuyenMai;
    }
    public KhuyenMai(String maKhuyenMai, String noiDungKhuyenMai, Integer tinhTrang, String ghiChu, Set chiTietKhuyenMais) {
       this.maKhuyenMai = maKhuyenMai;
       this.noiDungKhuyenMai = noiDungKhuyenMai;
       this.tinhTrang = tinhTrang;
       this.ghiChu = ghiChu;
       this.chiTietKhuyenMais = chiTietKhuyenMais;
    }
   
    public String getMaKhuyenMai() {
        return this.maKhuyenMai;
    }
    
    public void setMaKhuyenMai(String maKhuyenMai) {
        this.maKhuyenMai = maKhuyenMai;
    }
    public String getNoiDungKhuyenMai() {
        return this.noiDungKhuyenMai;
    }
    
    public void setNoiDungKhuyenMai(String noiDungKhuyenMai) {
        this.noiDungKhuyenMai = noiDungKhuyenMai;
    }
    public Integer getTinhTrang() {
        return this.tinhTrang;
    }
    
    public void setTinhTrang(Integer tinhTrang) {
        this.tinhTrang = tinhTrang;
    }
    public String getGhiChu() {
        return this.ghiChu;
    }
    
    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }
    public Set getChiTietKhuyenMais() {
        return this.chiTietKhuyenMais;
    }
    
    public void setChiTietKhuyenMais(Set chiTietKhuyenMais) {
        this.chiTietKhuyenMais = chiTietKhuyenMais;
    }




}


