package model.pojo;
// Generated Nov 23, 2012 11:16:33 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TinhTrangDonDatHang generated by hbm2java
 */
public class TinhTrangDonDatHang  implements java.io.Serializable {


     private int maTinhTrang;
     private String mota;
     private Set datHangs = new HashSet(0);

    public TinhTrangDonDatHang() {
    }

	
    public TinhTrangDonDatHang(int maTinhTrang) {
        this.maTinhTrang = maTinhTrang;
    }
    public TinhTrangDonDatHang(int maTinhTrang, String mota, Set datHangs) {
       this.maTinhTrang = maTinhTrang;
       this.mota = mota;
       this.datHangs = datHangs;
    }
   
    public int getMaTinhTrang() {
        return this.maTinhTrang;
    }
    
    public void setMaTinhTrang(int maTinhTrang) {
        this.maTinhTrang = maTinhTrang;
    }
    public String getMota() {
        return this.mota;
    }
    
    public void setMota(String mota) {
        this.mota = mota;
    }
    public Set getDatHangs() {
        return this.datHangs;
    }
    
    public void setDatHangs(Set datHangs) {
        this.datHangs = datHangs;
    }




}


